
FROM mcr.microsoft.com/devcontainers/base:noble@sha256:7ee7da33a68d997971660d91ecc8372e55a38a777c3c6bd6808daf91928052db

ENV DO_NOT_TRACK=1
ARG BUN_VERSION
ARG BUN_SHA256_X64
ARG BUN_SHA256_AARCH64
ARG vscode

RUN if [[ -z "$DEV_CONTAINER_CLI" ]] ; then printf "\nERROR: This Dockerfile needs to be built with VS Code !" && exit 1; else printf "VS Code is detected: $DEV_CONTAINER_CLI"; fi

RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends apt-utils dialog git curl xz-utils m4 inotify-tools \
       libwebkit2gtk-4.1-0 libgtk-3-0 libayatana-appindicator3-1 xvfb 2>&1 \
    && rm -rf /var/lib/apt/lists/*

COPY install.bash /tmp/install-bun.bash

RUN chmod +x /tmp/install-bun.bash \
    && /tmp/install-bun.bash "$BUN_VERSION" "$BUN_SHA256_X64" "$BUN_SHA256_AARCH64" \
    && rm /tmp/install-bun.bash
