FROM mcr.microsoft.com/devcontainers/base:noble

RUN apt-get update \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install git curl xz-utils m4 minify \
  && rm -rf /var/lib/apt/lists/* \
  && curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr/local bash \
  && ln -s /usr/local/bin/bun /usr/local/bin/node
